### ISSUE TITLE
Pronunciation of instruire incorrect

### ISSUE THREAD

**Issue by jech** [matej-kosik/conjugate#1]
The pronunciation of *instruire* is incorrect — the first vowel is a fron nasal, not a back one.

**Comment by matej-kosik** [comment]
That is on purpose:
http://matej-kosik.github.io/conjugate/IPA_subset.html
My transliteration captures the (nasal) vowel-shift that happened and dictionaries stubbornly ignore.

**Comment by jech** [comment]
> My transliteration captures the (nasal) vowel-shift that happened

Interesting.  In what part of France?

To my ear, [ã] en [ẽ] are clearly distinct, although [œ̃] has merged with
[ẽ], at least in fast speech.

**Comment by matej-kosik** [comment]
Well, for example here:
https://www.youtube.com/watch?v=dbyKzUM9H5c
the guy claims that there are three nasal vowels:
"ã", "ɛ̃", "ɔ̃"
As I listen to him:
- "ã" is clearly distinct from "ɛ̃", OK
- "ɛ̃" is clearly distinct from "ɔ̃", OK
but I do not hear any difference between "ã" and "ɔ̃".

I haven't found a recording yet, where I would clearly hear the difference.
As if, it was something people imagine but does not actually exist.
So far, I haven't joined this sect of imaginary vowel. :-)

**Comment by jech** [comment]
>  but I do not hear any difference between "ã" and "ɔ̃".

Try this:

  http://www.prononcer.net/voyelles-nasales-on-an-paires-minimales-francais-facile
